#Controller to control robot arm joints
robotic_arm:
  robot_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [link1_revolute, link2_revolute, link3_revolute, link4_revolute, link5_revolute,]

  #Controller to control end effector joints
  hand_ee_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [link6_1_prismatic, link6_2_prismatic]

  #Controller to continuously publish joint states/positions
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50